// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: NetworkInfo.proto
// Protobuf C++ Version: 6.31.0

#ifndef NetworkInfo_2eproto_2epb_2eh
#define NetworkInfo_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_NetworkInfo_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_NetworkInfo_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_NetworkInfo_2eproto;
}  // extern "C"
namespace openauto {
namespace btservice {
namespace proto {
enum AccessPointType : int;
extern const uint32_t AccessPointType_internal_data_[];
enum SecurityMode : int;
extern const uint32_t SecurityMode_internal_data_[];
class NetworkInfo;
struct NetworkInfoDefaultTypeInternal;
extern NetworkInfoDefaultTypeInternal _NetworkInfo_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull NetworkInfo_class_data_;
}  // namespace proto
}  // namespace btservice
}  // namespace openauto
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::openauto::btservice::proto::AccessPointType_internal_data_>
    internal::EnumTraitsImpl::value<::openauto::btservice::proto::AccessPointType>;
template <>
internal::EnumTraitsT<::openauto::btservice::proto::SecurityMode_internal_data_>
    internal::EnumTraitsImpl::value<::openauto::btservice::proto::SecurityMode>;
}  // namespace protobuf
}  // namespace google

namespace openauto {
namespace btservice {
namespace proto {
enum SecurityMode : int {
  UNKNOWN_SECURITY_MODE = 0,
  OPEN = 1,
  WEP_64 = 2,
  WEP_128 = 3,
  WPA_PERSONAL = 4,
  WPA2_PERSONAL = 8,
  WPA_WPA2_PERSONAL = 12,
  WPA_ENTERPRISE = 20,
  WPA2_ENTERPRISE = 24,
  WPA_WPA2_ENTERPRISE = 28,
};

extern const uint32_t SecurityMode_internal_data_[];
inline constexpr SecurityMode SecurityMode_MIN =
    static_cast<SecurityMode>(0);
inline constexpr SecurityMode SecurityMode_MAX =
    static_cast<SecurityMode>(28);
inline bool SecurityMode_IsValid(int value) {
  return 0 <= value && value <= 28 && ((286265631u >> value) & 1) != 0;
}
inline constexpr int SecurityMode_ARRAYSIZE = 28 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL SecurityMode_descriptor();
template <typename T>
const ::std::string& SecurityMode_Name(T value) {
  static_assert(::std::is_same<T, SecurityMode>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to SecurityMode_Name().");
  return ::google::protobuf::internal::NameOfEnum(SecurityMode_descriptor(), value);
}
inline bool SecurityMode_Parse(
    ::absl::string_view name, SecurityMode* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<SecurityMode>(SecurityMode_descriptor(), name,
                                           value);
}
enum AccessPointType : int {
  STATIC = 0,
  DYNAMIC = 1,
};

extern const uint32_t AccessPointType_internal_data_[];
inline constexpr AccessPointType AccessPointType_MIN =
    static_cast<AccessPointType>(0);
inline constexpr AccessPointType AccessPointType_MAX =
    static_cast<AccessPointType>(1);
inline bool AccessPointType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int AccessPointType_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL AccessPointType_descriptor();
template <typename T>
const ::std::string& AccessPointType_Name(T value) {
  static_assert(::std::is_same<T, AccessPointType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to AccessPointType_Name().");
  return AccessPointType_Name(static_cast<AccessPointType>(value));
}
template <>
inline const ::std::string& AccessPointType_Name(AccessPointType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AccessPointType_descriptor, 0, 1>(
      static_cast<int>(value));
}
inline bool AccessPointType_Parse(
    ::absl::string_view name, AccessPointType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<AccessPointType>(AccessPointType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class NetworkInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:openauto.btservice.proto.NetworkInfo) */ {
 public:
  inline NetworkInfo() : NetworkInfo(nullptr) {}
  ~NetworkInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NetworkInfo* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NetworkInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NetworkInfo(::google::protobuf::internal::ConstantInitialized);

  inline NetworkInfo(const NetworkInfo& from) : NetworkInfo(nullptr, from) {}
  inline NetworkInfo(NetworkInfo&& from) noexcept
      : NetworkInfo(nullptr, ::std::move(from)) {}
  inline NetworkInfo& operator=(const NetworkInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline NetworkInfo& operator=(NetworkInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NetworkInfo& default_instance() {
    return *reinterpret_cast<const NetworkInfo*>(
        &_NetworkInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(NetworkInfo& a, NetworkInfo& b) { a.Swap(&b); }
  inline void Swap(NetworkInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NetworkInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NetworkInfo* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NetworkInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NetworkInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NetworkInfo& from) { NetworkInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NetworkInfo* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "openauto.btservice.proto.NetworkInfo"; }

 protected:
  explicit NetworkInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  NetworkInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NetworkInfo& from);
  NetworkInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, NetworkInfo&& from) noexcept
      : NetworkInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSsidFieldNumber = 1,
    kPskFieldNumber = 2,
    kMacAddrFieldNumber = 3,
    kSecurityModeFieldNumber = 4,
    kApTypeFieldNumber = 5,
  };
  // required string ssid = 1;
  bool has_ssid() const;
  void clear_ssid() ;
  const ::std::string& ssid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ssid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ssid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ssid();
  void set_allocated_ssid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ssid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ssid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ssid();

  public:
  // required string psk = 2;
  bool has_psk() const;
  void clear_psk() ;
  const ::std::string& psk() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_psk(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_psk();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_psk();
  void set_allocated_psk(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_psk() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_psk(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_psk();

  public:
  // required string mac_addr = 3;
  bool has_mac_addr() const;
  void clear_mac_addr() ;
  const ::std::string& mac_addr() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_mac_addr(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_mac_addr();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_mac_addr();
  void set_allocated_mac_addr(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_mac_addr() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_mac_addr(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_mac_addr();

  public:
  // required .openauto.btservice.proto.SecurityMode security_mode = 4;
  bool has_security_mode() const;
  void clear_security_mode() ;
  ::openauto::btservice::proto::SecurityMode security_mode() const;
  void set_security_mode(::openauto::btservice::proto::SecurityMode value);

  private:
  ::openauto::btservice::proto::SecurityMode _internal_security_mode() const;
  void _internal_set_security_mode(::openauto::btservice::proto::SecurityMode value);

  public:
  // required .openauto.btservice.proto.AccessPointType ap_type = 5;
  bool has_ap_type() const;
  void clear_ap_type() ;
  ::openauto::btservice::proto::AccessPointType ap_type() const;
  void set_ap_type(::openauto::btservice::proto::AccessPointType value);

  private:
  ::openauto::btservice::proto::AccessPointType _internal_ap_type() const;
  void _internal_set_ap_type(::openauto::btservice::proto::AccessPointType value);

  public:
  // @@protoc_insertion_point(class_scope:openauto.btservice.proto.NetworkInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   2, 60,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const NetworkInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr ssid_;
    ::google::protobuf::internal::ArenaStringPtr psk_;
    ::google::protobuf::internal::ArenaStringPtr mac_addr_;
    int security_mode_;
    int ap_type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NetworkInfo_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull NetworkInfo_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NetworkInfo

// required string ssid = 1;
inline bool NetworkInfo::has_ssid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void NetworkInfo::clear_ssid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ssid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& NetworkInfo::ssid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:openauto.btservice.proto.NetworkInfo.ssid)
  return _internal_ssid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void NetworkInfo::set_ssid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ssid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:openauto.btservice.proto.NetworkInfo.ssid)
}
inline ::std::string* PROTOBUF_NONNULL NetworkInfo::mutable_ssid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_ssid();
  // @@protoc_insertion_point(field_mutable:openauto.btservice.proto.NetworkInfo.ssid)
  return _s;
}
inline const ::std::string& NetworkInfo::_internal_ssid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ssid_.Get();
}
inline void NetworkInfo::_internal_set_ssid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ssid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL NetworkInfo::_internal_mutable_ssid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.ssid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE NetworkInfo::release_ssid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:openauto.btservice.proto.NetworkInfo.ssid)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.ssid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ssid_.Set("", GetArena());
  }
  return released;
}
inline void NetworkInfo::set_allocated_ssid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.ssid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ssid_.IsDefault()) {
    _impl_.ssid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:openauto.btservice.proto.NetworkInfo.ssid)
}

// required string psk = 2;
inline bool NetworkInfo::has_psk() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void NetworkInfo::clear_psk() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.psk_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& NetworkInfo::psk() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:openauto.btservice.proto.NetworkInfo.psk)
  return _internal_psk();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void NetworkInfo::set_psk(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.psk_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:openauto.btservice.proto.NetworkInfo.psk)
}
inline ::std::string* PROTOBUF_NONNULL NetworkInfo::mutable_psk()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_psk();
  // @@protoc_insertion_point(field_mutable:openauto.btservice.proto.NetworkInfo.psk)
  return _s;
}
inline const ::std::string& NetworkInfo::_internal_psk() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.psk_.Get();
}
inline void NetworkInfo::_internal_set_psk(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.psk_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL NetworkInfo::_internal_mutable_psk() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.psk_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE NetworkInfo::release_psk() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:openauto.btservice.proto.NetworkInfo.psk)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.psk_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.psk_.Set("", GetArena());
  }
  return released;
}
inline void NetworkInfo::set_allocated_psk(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.psk_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.psk_.IsDefault()) {
    _impl_.psk_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:openauto.btservice.proto.NetworkInfo.psk)
}

// required string mac_addr = 3;
inline bool NetworkInfo::has_mac_addr() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void NetworkInfo::clear_mac_addr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mac_addr_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::std::string& NetworkInfo::mac_addr() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:openauto.btservice.proto.NetworkInfo.mac_addr)
  return _internal_mac_addr();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void NetworkInfo::set_mac_addr(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.mac_addr_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:openauto.btservice.proto.NetworkInfo.mac_addr)
}
inline ::std::string* PROTOBUF_NONNULL NetworkInfo::mutable_mac_addr()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_mac_addr();
  // @@protoc_insertion_point(field_mutable:openauto.btservice.proto.NetworkInfo.mac_addr)
  return _s;
}
inline const ::std::string& NetworkInfo::_internal_mac_addr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mac_addr_.Get();
}
inline void NetworkInfo::_internal_set_mac_addr(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.mac_addr_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL NetworkInfo::_internal_mutable_mac_addr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.mac_addr_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE NetworkInfo::release_mac_addr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:openauto.btservice.proto.NetworkInfo.mac_addr)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.mac_addr_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.mac_addr_.Set("", GetArena());
  }
  return released;
}
inline void NetworkInfo::set_allocated_mac_addr(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.mac_addr_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.mac_addr_.IsDefault()) {
    _impl_.mac_addr_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:openauto.btservice.proto.NetworkInfo.mac_addr)
}

// required .openauto.btservice.proto.SecurityMode security_mode = 4;
inline bool NetworkInfo::has_security_mode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void NetworkInfo::clear_security_mode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.security_mode_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::openauto::btservice::proto::SecurityMode NetworkInfo::security_mode() const {
  // @@protoc_insertion_point(field_get:openauto.btservice.proto.NetworkInfo.security_mode)
  return _internal_security_mode();
}
inline void NetworkInfo::set_security_mode(::openauto::btservice::proto::SecurityMode value) {
  _internal_set_security_mode(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:openauto.btservice.proto.NetworkInfo.security_mode)
}
inline ::openauto::btservice::proto::SecurityMode NetworkInfo::_internal_security_mode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::openauto::btservice::proto::SecurityMode>(_impl_.security_mode_);
}
inline void NetworkInfo::_internal_set_security_mode(::openauto::btservice::proto::SecurityMode value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::openauto::btservice::proto::SecurityMode_internal_data_));
                                          _impl_.security_mode_ = value;
}

// required .openauto.btservice.proto.AccessPointType ap_type = 5;
inline bool NetworkInfo::has_ap_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void NetworkInfo::clear_ap_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ap_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::openauto::btservice::proto::AccessPointType NetworkInfo::ap_type() const {
  // @@protoc_insertion_point(field_get:openauto.btservice.proto.NetworkInfo.ap_type)
  return _internal_ap_type();
}
inline void NetworkInfo::set_ap_type(::openauto::btservice::proto::AccessPointType value) {
  _internal_set_ap_type(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:openauto.btservice.proto.NetworkInfo.ap_type)
}
inline ::openauto::btservice::proto::AccessPointType NetworkInfo::_internal_ap_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::openauto::btservice::proto::AccessPointType>(_impl_.ap_type_);
}
inline void NetworkInfo::_internal_set_ap_type(::openauto::btservice::proto::AccessPointType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::openauto::btservice::proto::AccessPointType_internal_data_));
                                          _impl_.ap_type_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace btservice
}  // namespace openauto


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::openauto::btservice::proto::SecurityMode> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::openauto::btservice::proto::SecurityMode>() {
  return ::openauto::btservice::proto::SecurityMode_descriptor();
}
template <>
struct is_proto_enum<::openauto::btservice::proto::AccessPointType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::openauto::btservice::proto::AccessPointType>() {
  return ::openauto::btservice::proto::AccessPointType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // NetworkInfo_2eproto_2epb_2eh
