// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: NetworkInfo.proto
// Protobuf C++ Version: 6.31.0

#include "NetworkInfo.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace openauto {
namespace btservice {
namespace proto {

inline constexpr NetworkInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ssid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        psk_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        mac_addr_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        security_mode_{static_cast< ::openauto::btservice::proto::SecurityMode >(0)},
        ap_type_{static_cast< ::openauto::btservice::proto::AccessPointType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR NetworkInfo::NetworkInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(NetworkInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NetworkInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NetworkInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NetworkInfoDefaultTypeInternal() {}
  union {
    NetworkInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NetworkInfoDefaultTypeInternal _NetworkInfo_default_instance_;
}  // namespace proto
}  // namespace btservice
}  // namespace openauto
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_NetworkInfo_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_NetworkInfo_2eproto = nullptr;
const ::uint32_t
    TableStruct_NetworkInfo_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::openauto::btservice::proto::NetworkInfo, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::openauto::btservice::proto::NetworkInfo, _impl_.ssid_),
        PROTOBUF_FIELD_OFFSET(::openauto::btservice::proto::NetworkInfo, _impl_.psk_),
        PROTOBUF_FIELD_OFFSET(::openauto::btservice::proto::NetworkInfo, _impl_.mac_addr_),
        PROTOBUF_FIELD_OFFSET(::openauto::btservice::proto::NetworkInfo, _impl_.security_mode_),
        PROTOBUF_FIELD_OFFSET(::openauto::btservice::proto::NetworkInfo, _impl_.ap_type_),
        0,
        1,
        2,
        3,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::openauto::btservice::proto::NetworkInfo)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::openauto::btservice::proto::_NetworkInfo_default_instance_._instance,
};
const char descriptor_table_protodef_NetworkInfo_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021NetworkInfo.proto\022\030openauto.btservice."
    "proto\"\265\001\n\013NetworkInfo\022\014\n\004ssid\030\001 \002(\t\022\013\n\003p"
    "sk\030\002 \002(\t\022\020\n\010mac_addr\030\003 \002(\t\022=\n\rsecurity_m"
    "ode\030\004 \002(\0162&.openauto.btservice.proto.Sec"
    "urityMode\022:\n\007ap_type\030\005 \002(\0162).openauto.bt"
    "service.proto.AccessPointType*\312\001\n\014Securi"
    "tyMode\022\031\n\025UNKNOWN_SECURITY_MODE\020\000\022\010\n\004OPE"
    "N\020\001\022\n\n\006WEP_64\020\002\022\013\n\007WEP_128\020\003\022\020\n\014WPA_PERS"
    "ONAL\020\004\022\021\n\rWPA2_PERSONAL\020\010\022\025\n\021WPA_WPA2_PE"
    "RSONAL\020\014\022\022\n\016WPA_ENTERPRISE\020\024\022\023\n\017WPA2_ENT"
    "ERPRISE\020\030\022\027\n\023WPA_WPA2_ENTERPRISE\020\034**\n\017Ac"
    "cessPointType\022\n\n\006STATIC\020\000\022\013\n\007DYNAMIC\020\001"
};
static ::absl::once_flag descriptor_table_NetworkInfo_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_NetworkInfo_2eproto = {
    false,
    false,
    478,
    descriptor_table_protodef_NetworkInfo_2eproto,
    "NetworkInfo.proto",
    &descriptor_table_NetworkInfo_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_NetworkInfo_2eproto::offsets,
    file_level_enum_descriptors_NetworkInfo_2eproto,
    file_level_service_descriptors_NetworkInfo_2eproto,
};
namespace openauto {
namespace btservice {
namespace proto {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL SecurityMode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_NetworkInfo_2eproto);
  return file_level_enum_descriptors_NetworkInfo_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t SecurityMode_internal_data_[] = {
    327680u, 32u, 8945800u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL AccessPointType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_NetworkInfo_2eproto);
  return file_level_enum_descriptors_NetworkInfo_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t AccessPointType_internal_data_[] = {
    131072u, 0u, };
// ===================================================================

class NetworkInfo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<NetworkInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000001f) ^ 0x0000001f) != 0;
  }
};

NetworkInfo::NetworkInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NetworkInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:openauto.btservice.proto.NetworkInfo)
}
PROTOBUF_NDEBUG_INLINE NetworkInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::openauto::btservice::proto::NetworkInfo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ssid_(arena, from.ssid_),
        psk_(arena, from.psk_),
        mac_addr_(arena, from.mac_addr_) {}

NetworkInfo::NetworkInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NetworkInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NetworkInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NetworkInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, security_mode_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, security_mode_),
           offsetof(Impl_, ap_type_) -
               offsetof(Impl_, security_mode_) +
               sizeof(Impl_::ap_type_));

  // @@protoc_insertion_point(copy_constructor:openauto.btservice.proto.NetworkInfo)
}
PROTOBUF_NDEBUG_INLINE NetworkInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        ssid_(arena),
        psk_(arena),
        mac_addr_(arena) {}

inline void NetworkInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, security_mode_),
           0,
           offsetof(Impl_, ap_type_) -
               offsetof(Impl_, security_mode_) +
               sizeof(Impl_::ap_type_));
}
NetworkInfo::~NetworkInfo() {
  // @@protoc_insertion_point(destructor:openauto.btservice.proto.NetworkInfo)
  SharedDtor(*this);
}
inline void NetworkInfo::SharedDtor(MessageLite& self) {
  NetworkInfo& this_ = static_cast<NetworkInfo&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ssid_.Destroy();
  this_._impl_.psk_.Destroy();
  this_._impl_.mac_addr_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL NetworkInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NetworkInfo(arena);
}
constexpr auto NetworkInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NetworkInfo),
                                            alignof(NetworkInfo));
}
constexpr auto NetworkInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NetworkInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          NetworkInfo::IsInitializedImpl,
          &NetworkInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NetworkInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NetworkInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NetworkInfo>(), &NetworkInfo::ByteSizeLong,
              &NetworkInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_._cached_size_),
          false,
      },
      &NetworkInfo::kDescriptorMethods,
      &descriptor_table_NetworkInfo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NetworkInfo_class_data_ =
        NetworkInfo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NetworkInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NetworkInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NetworkInfo_class_data_.tc_table);
  return NetworkInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 2, 60, 2>
NetworkInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    NetworkInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::openauto::btservice::proto::NetworkInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required string ssid = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_.ssid_)}},
    // required string psk = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_.psk_)}},
    // required string mac_addr = 3;
    {::_pbi::TcParser::FastSS1,
     {26, 2, 0, PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_.mac_addr_)}},
    // required .openauto.btservice.proto.SecurityMode security_mode = 4;
    {::_pbi::TcParser::FastEvS1,
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_.security_mode_)}},
    // required .openauto.btservice.proto.AccessPointType ap_type = 5;
    {::_pbi::TcParser::FastEr0S1,
     {40, 4, 1, PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_.ap_type_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // required string ssid = 1;
    {PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_.ssid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string psk = 2;
    {PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_.psk_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string mac_addr = 3;
    {PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_.mac_addr_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required .openauto.btservice.proto.SecurityMode security_mode = 4;
    {PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_.security_mode_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnum)},
    // required .openauto.btservice.proto.AccessPointType ap_type = 5;
    {PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_.ap_type_), _Internal::kHasBitsOffset + 4, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
  }},
  {{
      {::_pbi::FieldAuxEnumData{}, ::openauto::btservice::proto::SecurityMode_internal_data_},
      {0, 1},
  }},
  {{
    "\44\4\3\10\0\0\0\0"
    "openauto.btservice.proto.NetworkInfo"
    "ssid"
    "psk"
    "mac_addr"
  }},
};
PROTOBUF_NOINLINE void NetworkInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:openauto.btservice.proto.NetworkInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.ssid_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.psk_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _impl_.mac_addr_.ClearNonDefaultToEmpty();
    }
  }
  if ((cached_has_bits & 0x00000018u) != 0) {
    ::memset(&_impl_.security_mode_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.ap_type_) -
        reinterpret_cast<char*>(&_impl_.security_mode_)) + sizeof(_impl_.ap_type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NetworkInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NetworkInfo& this_ = static_cast<const NetworkInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NetworkInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NetworkInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:openauto.btservice.proto.NetworkInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required string ssid = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_ssid();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "openauto.btservice.proto.NetworkInfo.ssid");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // required string psk = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    const ::std::string& _s = this_._internal_psk();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "openauto.btservice.proto.NetworkInfo.psk");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // required string mac_addr = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    const ::std::string& _s = this_._internal_mac_addr();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "openauto.btservice.proto.NetworkInfo.mac_addr");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // required .openauto.btservice.proto.SecurityMode security_mode = 4;
  if ((cached_has_bits & 0x00000008u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        4, this_._internal_security_mode(), target);
  }

  // required .openauto.btservice.proto.AccessPointType ap_type = 5;
  if ((cached_has_bits & 0x00000010u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        5, this_._internal_ap_type(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openauto.btservice.proto.NetworkInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NetworkInfo::ByteSizeLong(const MessageLite& base) {
  const NetworkInfo& this_ = static_cast<const NetworkInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NetworkInfo::ByteSizeLong() const {
  const NetworkInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:openauto.btservice.proto.NetworkInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    // required string ssid = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_ssid());
    }
    // required string psk = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_psk());
    }
    // required string mac_addr = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_mac_addr());
    }
    // required .openauto.btservice.proto.SecurityMode security_mode = 4;
    if ((cached_has_bits & 0x00000008u) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_security_mode());
    }
    // required .openauto.btservice.proto.AccessPointType ap_type = 5;
    if ((cached_has_bits & 0x00000010u) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_ap_type());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NetworkInfo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NetworkInfo*>(&to_msg);
  auto& from = static_cast<const NetworkInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:openauto.btservice.proto.NetworkInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_ssid(from._internal_ssid());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_internal_set_psk(from._internal_psk());
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_internal_set_mac_addr(from._internal_mac_addr());
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      _this->_impl_.security_mode_ = from._impl_.security_mode_;
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      _this->_impl_.ap_type_ = from._impl_.ap_type_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NetworkInfo::CopyFrom(const NetworkInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openauto.btservice.proto.NetworkInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool NetworkInfo::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const NetworkInfo&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void NetworkInfo::InternalSwap(NetworkInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ssid_, &other->_impl_.ssid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.psk_, &other->_impl_.psk_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.mac_addr_, &other->_impl_.mac_addr_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_.ap_type_)
      + sizeof(NetworkInfo::_impl_.ap_type_)
      - PROTOBUF_FIELD_OFFSET(NetworkInfo, _impl_.security_mode_)>(
          reinterpret_cast<char*>(&_impl_.security_mode_),
          reinterpret_cast<char*>(&other->_impl_.security_mode_));
}

::google::protobuf::Metadata NetworkInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace btservice
}  // namespace openauto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_NetworkInfo_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
