// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SocketInfoRequest.proto
// Protobuf C++ Version: 6.31.0

#include "SocketInfoRequest.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace openauto {
namespace btservice {
namespace proto {

inline constexpr SocketInfoRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ip_address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        port_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR SocketInfoRequest::SocketInfoRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SocketInfoRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SocketInfoRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SocketInfoRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SocketInfoRequestDefaultTypeInternal() {}
  union {
    SocketInfoRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SocketInfoRequestDefaultTypeInternal _SocketInfoRequest_default_instance_;
}  // namespace proto
}  // namespace btservice
}  // namespace openauto
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_SocketInfoRequest_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_SocketInfoRequest_2eproto = nullptr;
const ::uint32_t
    TableStruct_SocketInfoRequest_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::openauto::btservice::proto::SocketInfoRequest, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::openauto::btservice::proto::SocketInfoRequest, _impl_.ip_address_),
        PROTOBUF_FIELD_OFFSET(::openauto::btservice::proto::SocketInfoRequest, _impl_.port_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::openauto::btservice::proto::SocketInfoRequest)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::openauto::btservice::proto::_SocketInfoRequest_default_instance_._instance,
};
const char descriptor_table_protodef_SocketInfoRequest_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027SocketInfoRequest.proto\022\030openauto.btse"
    "rvice.proto\"5\n\021SocketInfoRequest\022\022\n\nip_a"
    "ddress\030\001 \002(\t\022\014\n\004port\030\002 \001(\r"
};
static ::absl::once_flag descriptor_table_SocketInfoRequest_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_SocketInfoRequest_2eproto = {
    false,
    false,
    106,
    descriptor_table_protodef_SocketInfoRequest_2eproto,
    "SocketInfoRequest.proto",
    &descriptor_table_SocketInfoRequest_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_SocketInfoRequest_2eproto::offsets,
    file_level_enum_descriptors_SocketInfoRequest_2eproto,
    file_level_service_descriptors_SocketInfoRequest_2eproto,
};
namespace openauto {
namespace btservice {
namespace proto {
// ===================================================================

class SocketInfoRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SocketInfoRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SocketInfoRequest, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

SocketInfoRequest::SocketInfoRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SocketInfoRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:openauto.btservice.proto.SocketInfoRequest)
}
PROTOBUF_NDEBUG_INLINE SocketInfoRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::openauto::btservice::proto::SocketInfoRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ip_address_(arena, from.ip_address_) {}

SocketInfoRequest::SocketInfoRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SocketInfoRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SocketInfoRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SocketInfoRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.port_ = from._impl_.port_;

  // @@protoc_insertion_point(copy_constructor:openauto.btservice.proto.SocketInfoRequest)
}
PROTOBUF_NDEBUG_INLINE SocketInfoRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        ip_address_(arena) {}

inline void SocketInfoRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.port_ = {};
}
SocketInfoRequest::~SocketInfoRequest() {
  // @@protoc_insertion_point(destructor:openauto.btservice.proto.SocketInfoRequest)
  SharedDtor(*this);
}
inline void SocketInfoRequest::SharedDtor(MessageLite& self) {
  SocketInfoRequest& this_ = static_cast<SocketInfoRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ip_address_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SocketInfoRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SocketInfoRequest(arena);
}
constexpr auto SocketInfoRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SocketInfoRequest),
                                            alignof(SocketInfoRequest));
}
constexpr auto SocketInfoRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SocketInfoRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          SocketInfoRequest::IsInitializedImpl,
          &SocketInfoRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SocketInfoRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SocketInfoRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SocketInfoRequest>(), &SocketInfoRequest::ByteSizeLong,
              &SocketInfoRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SocketInfoRequest, _impl_._cached_size_),
          false,
      },
      &SocketInfoRequest::kDescriptorMethods,
      &descriptor_table_SocketInfoRequest_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SocketInfoRequest_class_data_ =
        SocketInfoRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SocketInfoRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SocketInfoRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SocketInfoRequest_class_data_.tc_table);
  return SocketInfoRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 61, 2>
SocketInfoRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SocketInfoRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SocketInfoRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::openauto::btservice::proto::SocketInfoRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional uint32 port = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SocketInfoRequest, _impl_.port_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(SocketInfoRequest, _impl_.port_)}},
    // required string ip_address = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SocketInfoRequest, _impl_.ip_address_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string ip_address = 1;
    {PROTOBUF_FIELD_OFFSET(SocketInfoRequest, _impl_.ip_address_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional uint32 port = 2;
    {PROTOBUF_FIELD_OFFSET(SocketInfoRequest, _impl_.port_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\52\12\0\0\0\0\0\0"
    "openauto.btservice.proto.SocketInfoRequest"
    "ip_address"
  }},
};
PROTOBUF_NOINLINE void SocketInfoRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:openauto.btservice.proto.SocketInfoRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.ip_address_.ClearNonDefaultToEmpty();
  }
  _impl_.port_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SocketInfoRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SocketInfoRequest& this_ = static_cast<const SocketInfoRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SocketInfoRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SocketInfoRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:openauto.btservice.proto.SocketInfoRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required string ip_address = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_ip_address();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "openauto.btservice.proto.SocketInfoRequest.ip_address");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional uint32 port = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_port(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openauto.btservice.proto.SocketInfoRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SocketInfoRequest::ByteSizeLong(const MessageLite& base) {
  const SocketInfoRequest& this_ = static_cast<const SocketInfoRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SocketInfoRequest::ByteSizeLong() const {
  const SocketInfoRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:openauto.btservice.proto.SocketInfoRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // required string ip_address = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_ip_address());
    }
  }
   {
    // optional uint32 port = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_port());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SocketInfoRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SocketInfoRequest*>(&to_msg);
  auto& from = static_cast<const SocketInfoRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:openauto.btservice.proto.SocketInfoRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_ip_address(from._internal_ip_address());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.port_ = from._impl_.port_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SocketInfoRequest::CopyFrom(const SocketInfoRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openauto.btservice.proto.SocketInfoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SocketInfoRequest::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const SocketInfoRequest&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void SocketInfoRequest::InternalSwap(SocketInfoRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ip_address_, &other->_impl_.ip_address_, arena);
  swap(_impl_.port_, other->_impl_.port_);
}

::google::protobuf::Metadata SocketInfoRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace btservice
}  // namespace openauto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_SocketInfoRequest_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
