// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SocketInfoResponse.proto
// Protobuf C++ Version: 6.31.0

#include "SocketInfoResponse.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace openauto {
namespace btservice {
namespace proto {

inline constexpr SocketInfoResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ip_address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        port_{0},
        status_{static_cast< ::openauto::btservice::proto::Status >(1)} {}

template <typename>
PROTOBUF_CONSTEXPR SocketInfoResponse::SocketInfoResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SocketInfoResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SocketInfoResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SocketInfoResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SocketInfoResponseDefaultTypeInternal() {}
  union {
    SocketInfoResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SocketInfoResponseDefaultTypeInternal _SocketInfoResponse_default_instance_;
}  // namespace proto
}  // namespace btservice
}  // namespace openauto
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_SocketInfoResponse_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_SocketInfoResponse_2eproto = nullptr;
const ::uint32_t
    TableStruct_SocketInfoResponse_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::openauto::btservice::proto::SocketInfoResponse, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::openauto::btservice::proto::SocketInfoResponse, _impl_.ip_address_),
        PROTOBUF_FIELD_OFFSET(::openauto::btservice::proto::SocketInfoResponse, _impl_.port_),
        PROTOBUF_FIELD_OFFSET(::openauto::btservice::proto::SocketInfoResponse, _impl_.status_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::openauto::btservice::proto::SocketInfoResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::openauto::btservice::proto::_SocketInfoResponse_default_instance_._instance,
};
const char descriptor_table_protodef_SocketInfoResponse_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030SocketInfoResponse.proto\022\030openauto.bts"
    "ervice.proto\"h\n\022SocketInfoResponse\022\022\n\nip"
    "_address\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\0220\n\006status\030\003"
    " \002(\0162 .openauto.btservice.proto.Status*\242"
    "\004\n\006Status\022\036\n\032STATUS_UNSOLICITED_MESSAGE\020"
    "\001\022\022\n\016STATUS_SUCCESS\020\000\022)\n\034STATUS_NO_COMPA"
    "TIBLE_VERSION\020\377\377\377\377\377\377\377\377\377\001\022-\n STATUS_WIFI_"
    "INACCESSIBLE_CHANNEL\020\376\377\377\377\377\377\377\377\377\001\022.\n!STATU"
    "S_WIFI_INCORRECT_CREDENTIALS\020\375\377\377\377\377\377\377\377\377\001\022"
    ".\n!STATUS_PROJECTION_ALREADY_STARTED\020\374\377\377"
    "\377\377\377\377\377\377\001\022!\n\024STATUS_WIFI_DISABLED\020\373\377\377\377\377\377\377\377"
    "\377\001\022(\n\033STATUS_WIFI_NOT_YET_STARTED\020\372\377\377\377\377\377"
    "\377\377\377\001\022 \n\023STATUS_INVALID_HOST\020\371\377\377\377\377\377\377\377\377\001\022."
    "\n!STATUS_NO_SUPPORTED_WIFI_CHANNELS\020\370\377\377\377"
    "\377\377\377\377\377\001\0224\n\'STATUS_INSTRUCT_USER_TO_CHECK_"
    "THE_PHONE\020\367\377\377\377\377\377\377\377\377\001\022\'\n\032STATUS_PHONE_WIF"
    "I_DISABLED\020\366\377\377\377\377\377\377\377\377\001\022,\n\037STATUS_WIFI_NET"
    "WORK_UNAVAILABLE\020\365\377\377\377\377\377\377\377\377\001"
};
static ::absl::once_flag descriptor_table_SocketInfoResponse_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_SocketInfoResponse_2eproto = {
    false,
    false,
    707,
    descriptor_table_protodef_SocketInfoResponse_2eproto,
    "SocketInfoResponse.proto",
    &descriptor_table_SocketInfoResponse_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_SocketInfoResponse_2eproto::offsets,
    file_level_enum_descriptors_SocketInfoResponse_2eproto,
    file_level_service_descriptors_SocketInfoResponse_2eproto,
};
namespace openauto {
namespace btservice {
namespace proto {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_SocketInfoResponse_2eproto);
  return file_level_enum_descriptors_SocketInfoResponse_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Status_internal_data_[] = {
    917493u, 0u, };
// ===================================================================

class SocketInfoResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SocketInfoResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SocketInfoResponse, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000004) ^ 0x00000004) != 0;
  }
};

SocketInfoResponse::SocketInfoResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SocketInfoResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:openauto.btservice.proto.SocketInfoResponse)
}
PROTOBUF_NDEBUG_INLINE SocketInfoResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::openauto::btservice::proto::SocketInfoResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ip_address_(arena, from.ip_address_) {}

SocketInfoResponse::SocketInfoResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SocketInfoResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SocketInfoResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SocketInfoResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, port_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, port_),
           offsetof(Impl_, status_) -
               offsetof(Impl_, port_) +
               sizeof(Impl_::status_));

  // @@protoc_insertion_point(copy_constructor:openauto.btservice.proto.SocketInfoResponse)
}
PROTOBUF_NDEBUG_INLINE SocketInfoResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        ip_address_(arena),
        status_{static_cast< ::openauto::btservice::proto::Status >(1)} {}

inline void SocketInfoResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.port_ = {};
}
SocketInfoResponse::~SocketInfoResponse() {
  // @@protoc_insertion_point(destructor:openauto.btservice.proto.SocketInfoResponse)
  SharedDtor(*this);
}
inline void SocketInfoResponse::SharedDtor(MessageLite& self) {
  SocketInfoResponse& this_ = static_cast<SocketInfoResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ip_address_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SocketInfoResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SocketInfoResponse(arena);
}
constexpr auto SocketInfoResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SocketInfoResponse),
                                            alignof(SocketInfoResponse));
}
constexpr auto SocketInfoResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SocketInfoResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          SocketInfoResponse::IsInitializedImpl,
          &SocketInfoResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SocketInfoResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SocketInfoResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SocketInfoResponse>(), &SocketInfoResponse::ByteSizeLong,
              &SocketInfoResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SocketInfoResponse, _impl_._cached_size_),
          false,
      },
      &SocketInfoResponse::kDescriptorMethods,
      &descriptor_table_SocketInfoResponse_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SocketInfoResponse_class_data_ =
        SocketInfoResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SocketInfoResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SocketInfoResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SocketInfoResponse_class_data_.tc_table);
  return SocketInfoResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 62, 2>
SocketInfoResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SocketInfoResponse, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    SocketInfoResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::openauto::btservice::proto::SocketInfoResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string ip_address = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SocketInfoResponse, _impl_.ip_address_)}},
    // optional int32 port = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SocketInfoResponse, _impl_.port_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(SocketInfoResponse, _impl_.port_)}},
    // required .openauto.btservice.proto.Status status = 3;
    {::_pbi::TcParser::FastErS1,
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(SocketInfoResponse, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string ip_address = 1;
    {PROTOBUF_FIELD_OFFSET(SocketInfoResponse, _impl_.ip_address_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional int32 port = 2;
    {PROTOBUF_FIELD_OFFSET(SocketInfoResponse, _impl_.port_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // required .openauto.btservice.proto.Status status = 3;
    {PROTOBUF_FIELD_OFFSET(SocketInfoResponse, _impl_.status_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
  }},
  {{
      {-11, 1},
  }},
  {{
    "\53\12\0\0\0\0\0\0"
    "openauto.btservice.proto.SocketInfoResponse"
    "ip_address"
  }},
};
PROTOBUF_NOINLINE void SocketInfoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:openauto.btservice.proto.SocketInfoResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.ip_address_.ClearNonDefaultToEmpty();
  }
  if ((cached_has_bits & 0x00000006u) != 0) {
    _impl_.port_ = 0;
    _impl_.status_ = 1;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SocketInfoResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SocketInfoResponse& this_ = static_cast<const SocketInfoResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SocketInfoResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SocketInfoResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:openauto.btservice.proto.SocketInfoResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string ip_address = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_ip_address();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "openauto.btservice.proto.SocketInfoResponse.ip_address");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional int32 port = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_port(), target);
  }

  // required .openauto.btservice.proto.Status status = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        3, this_._internal_status(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openauto.btservice.proto.SocketInfoResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SocketInfoResponse::ByteSizeLong(const MessageLite& base) {
  const SocketInfoResponse& this_ = static_cast<const SocketInfoResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SocketInfoResponse::ByteSizeLong() const {
  const SocketInfoResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:openauto.btservice.proto.SocketInfoResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // optional string ip_address = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_ip_address());
    }
    // optional int32 port = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_port());
    }
  }
   {
    // required .openauto.btservice.proto.Status status = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SocketInfoResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SocketInfoResponse*>(&to_msg);
  auto& from = static_cast<const SocketInfoResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:openauto.btservice.proto.SocketInfoResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_ip_address(from._internal_ip_address());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.port_ = from._impl_.port_;
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.status_ = from._impl_.status_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SocketInfoResponse::CopyFrom(const SocketInfoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openauto.btservice.proto.SocketInfoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SocketInfoResponse::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const SocketInfoResponse&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void SocketInfoResponse::InternalSwap(SocketInfoResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ip_address_, &other->_impl_.ip_address_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SocketInfoResponse, _impl_.status_)
      + sizeof(SocketInfoResponse::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(SocketInfoResponse, _impl_.port_)>(
          reinterpret_cast<char*>(&_impl_.port_),
          reinterpret_cast<char*>(&other->_impl_.port_));
}

::google::protobuf::Metadata SocketInfoResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace btservice
}  // namespace openauto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_SocketInfoResponse_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
